##  Hitelbírálati scorecard Merkantil Bank

#### Adatok betöltése (woe értékek)

In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_bc050f45180b4c1bb8886542b85a43fe = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='4DLJlzwg8MgMq4PD2ex7uQpqlXiuULzTTHhXPHtmCwyt',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_bc050f45180b4c1bb8886542b85a43fe.get_object(Bucket='merkantil-donotdelete-pr-8oggzmz2hvumtu',Key='Merkaintil_input.xlsx')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_0 = pd.read_excel(body)
df_data_0.head()


woe_customer_type  woe_product_type    woe_pc   woe_age  woe_sales_channel  \
0          -0.026821         -0.126048 -0.074399  0.583705           0.213637   
1          -0.026821         -0.126048 -0.191949 -1.130577          -0.911849   
2          -0.026821         -0.126048  0.684625  0.583705           0.213637   
3          -0.026821         -0.126048  0.684625  0.583705           0.213637   
4          -0.026821         -0.126048 -0.191949 -1.130577          -0.911849   

   woe_nace_risk  DPD90_12m  
0       0.691410          0  
1       0.691410          0  
2       0.691410          0  
3       0.691410          0  
4      -0.948982          0

In [2]:

df_data_0.shape

(10422, 7)

#### Adatok előkészítése

In [3]:
import numpy as np

In [4]:
X = np.asarray(df_data_0[['woe_customer_type', 'woe_product_type', 'woe_pc', 'woe_age', 'woe_sales_channel', 'woe_nace_risk']])
X[0:5]

array([[-0.02682054, -0.12604817, -0.0743993 ,  0.58370529,  0.21363652,
         0.6914096 ],
       [-0.02682054, -0.12604817, -0.19194917, -1.13057728, -0.91184899,
         0.6914096 ],
       [-0.02682054, -0.12604817,  0.68462526,  0.58370529,  0.21363652,
         0.6914096 ],
       [-0.02682054, -0.12604817,  0.68462526,  0.58370529,  0.21363652,
         0.6914096 ],
       [-0.02682054, -0.12604817, -0.19194917, -1.13057728, -0.91184899,
        -0.9489822 ]])

In [5]:
y = np.asarray(df_data_0['DPD90_12m'])
y [0:5]

array([0, 0, 0, 0, 0])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=4)

#### Modellezés

In [7]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
yhat = LR.predict_proba(X_test)
yhat

array([[0.85141452, 0.14858548],
       [0.99497205, 0.00502795],
       [0.9957332 , 0.0042668 ],
       ...,
       [0.98735029, 0.01264971],
       [0.99223364, 0.00776636],
       [0.98735029, 0.01264971]])

In [9]:
yhat1 = LR.predict_proba(X_train)
yhat1

array([[0.92405477, 0.07594523],
       [0.9813003 , 0.0186997 ],
       [0.99223364, 0.00776636],
       ...,
       [0.9771331 , 0.0228669 ],
       [0.98054198, 0.01945802],
       [0.8912219 , 0.1087781 ]])

#### Modell ereje teszt mintán

In [10]:
tech, y_predicted = zip(*yhat)
y_predicted

(0.14858548469354718,
 0.005027952588685802,
 0.004266798767236677,
 0.03876566966465763,
 0.045400470610182195,
 0.008442202764672526,
 0.022866898808933205,
 0.031795409871245496,
 0.04228740291849894,
 0.04349340748819124,
 0.022373295065228928,
 0.028469364719113224,
 0.02112962818279413,
 0.004266798767236677,
 0.009146064431569328,
 0.035864853353727445,
 0.0253764983423476,
 0.009146064431569328,
 0.017974967280105395,
 0.017974967280105395,
 0.009146064431569328,
 0.00716790812713207,
 0.009499677600032763,
 0.03712646460223897,
 0.009146064431569328,
 0.12887721956901133,
 0.004266798767236677,
 0.06787397050994026,
 0.04395939992706841,
 0.00776635868194259,
 0.011183839403433472,
 0.04444258144282605,
 0.03876566966465763,
 0.005027952588685802,
 0.00776635868194259,
 0.017619208774689046,
 0.008442202764672526,
 0.09823992686050957,
 0.02903296860658512,
 0.08516827135744919,
 0.0253764983423476,
 0.022866898808933205,
 0.009146064431569328,
 0.008442202764672526,
 0.007766

In [11]:
from sklearn.metrics import roc_auc_score
roc=roc_auc_score(y_test, y_predicted)
roc

0.7550652072659524

In [12]:
gini=2*roc-1
gini

0.5101304145319048

#### Modell ereje train mintán

In [13]:
tech1, y_predicted_train = zip(*yhat1)
y_predicted_train

(0.07594522540310938,
 0.01869970463868627,
 0.00776635868194259,
 0.019073477869615846,
 0.021601770691455996,
 0.035419794161753004,
 0.093858557991814,
 0.07316727056825051,
 0.019458018659474687,
 0.009146064431569328,
 0.009146064431569328,
 0.02892678591963563,
 0.035864853353727445,
 0.005027952588685802,
 0.010747201379306246,
 0.027911805801480335,
 0.0629216664279526,
 0.004266798767236677,
 0.008442202764672526,
 0.05152296469617574,
 0.008442202764672526,
 0.04698116924955499,
 0.026279218989776188,
 0.08516827135744919,
 0.017619208774689046,
 0.00776635868194259,
 0.004266798767236677,
 0.08516827135744919,
 0.008945926352889872,
 0.004266798767236677,
 0.00776635868194259,
 0.007460223032877725,
 0.019118610880725875,
 0.00716790812713207,
 0.08516827135744919,
 0.022866898808933205,
 0.020241319056008924,
 0.009146064431569328,
 0.022866898808933205,
 0.019458018659474687,
 0.009146064431569328,
 0.011677083443334634,
 0.022846739229716594,
 0.0253764983423476,
 0.00716

In [14]:
roc1=roc_auc_score(y_train, y_predicted_train)
gini1=2*roc1-1
gini1

0.5334763739593833

#### train és teszt minta gini-je hasonló így nincs overfit, 50% körüli Gini alapján a model nem mondható nagyon erősnek, de használható

### Modell paraméterek:

In [15]:
print(LR.coef_)

[[-0.45508821 -0.47267221 -0.68728712 -0.80548057 -0.34634119 -0.99944051]]


In [16]:
print(LR.intercept_)

[-3.65377567]


In [17]:
predictions_final = LR.predict_proba(X)
predictions_final

array([[0.9915578 , 0.0084422 ],
       [0.94856445, 0.05143555],
       [0.99497205, 0.00502795],
       ...,
       [0.99303625, 0.00696375],
       [0.9921191 , 0.0078809 ],
       [0.77076708, 0.22923292]])

#### Innentől paraméterek felhasználásával excelben folytatom

#### Teljes Gini

In [18]:
tech1, y_predicted_all = zip(*predictions_final)
y_predicted_all

(0.008442202764672526,
 0.051435549663949316,
 0.005027952588685802,
 0.005027952588685802,
 0.218377588232273,
 0.04698116924955497,
 0.012649707388472825,
 0.005027952588685802,
 0.02112962818279413,
 0.027911805801480335,
 0.004441332601399709,
 0.008442202764672526,
 0.04698116924955497,
 0.045400470610182195,
 0.005027952588685802,
 0.019073477869615846,
 0.007460223032877725,
 0.009146064431569328,
 0.010532959662273548,
 0.045400470610182195,
 0.07908083594662664,
 0.012649707388472825,
 0.012649707388472825,
 0.004441332601399709,
 0.03541979416175299,
 0.009146064431569328,
 0.009146064431569328,
 0.20704028926744547,
 0.012649707388472825,
 0.045400470610182195,
 0.04349340748819124,
 0.017619208774689046,
 0.0629216664279526,
 0.008442202764672526,
 0.04698116924955497,
 0.04349340748819124,
 0.1753323238887945,
 0.009146064431569328,
 0.0629216664279526,
 0.012649707388472825,
 0.012649707388472825,
 0.02892678591963563,
 0.022866898808933205,
 0.022866898808933205,
 0.0354

In [19]:
roc2=roc_auc_score(y, y_predicted_all)
gini2=2*roc2-1
gini2

0.5265528420476089